(function() {var implementors = {};
implementors["cjdns_admin"] = [{"text":"impl Freeze for Opts","synthetic":true,"types":[]},{"text":"impl !Freeze for Connection","synthetic":true,"types":[]},{"text":"impl Freeze for ArgValues","synthetic":true,"types":[]},{"text":"impl Freeze for Arg","synthetic":true,"types":[]},{"text":"impl Freeze for Args","synthetic":true,"types":[]},{"text":"impl Freeze for Func","synthetic":true,"types":[]},{"text":"impl Freeze for Funcs","synthetic":true,"types":[]},{"text":"impl Freeze for Error","synthetic":true,"types":[]},{"text":"impl Freeze for ArgValue","synthetic":true,"types":[]},{"text":"impl Freeze for ArgType","synthetic":true,"types":[]},{"text":"impl Freeze for ReturnValue","synthetic":true,"types":[]},{"text":"impl Freeze for Empty","synthetic":true,"types":[]}];
implementors["cjdns_ann"] = [{"text":"impl Freeze for Announcement","synthetic":true,"types":[]},{"text":"impl Freeze for AnnouncementHeader","synthetic":true,"types":[]},{"text":"impl Freeze for AnnouncementPacket","synthetic":true,"types":[]},{"text":"impl Freeze for Entity","synthetic":true,"types":[]}];
implementors["cjdns_bencode"] = [{"text":"impl Freeze for BValue","synthetic":true,"types":[]}];
implementors["cjdns_bytes"] = [{"text":"impl&lt;'a&gt; Freeze for Reader&lt;'a&gt;","synthetic":true,"types":[]},{"text":"impl Freeze for Writer","synthetic":true,"types":[]},{"text":"impl Freeze for ParseError","synthetic":true,"types":[]},{"text":"impl Freeze for SerializeError","synthetic":true,"types":[]},{"text":"impl Freeze for ExpectedSize","synthetic":true,"types":[]}];
implementors["cjdns_core"] = [{"text":"impl Freeze for EncodingScheme","synthetic":true,"types":[]},{"text":"impl Freeze for EncodingSchemeForm","synthetic":true,"types":[]},{"text":"impl&lt;'a, L&gt; Freeze for PathHop&lt;'a, L&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: Freeze,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl&lt;L&gt; Freeze for RoutingLabel&lt;L&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;L: Freeze,&nbsp;</span>","synthetic":true,"types":[]},{"text":"impl Freeze for SchemeValidationError","synthetic":true,"types":[]},{"text":"impl Freeze for EncodingSerializationError","synthetic":true,"types":[]},{"text":"impl Freeze for LabelError","synthetic":true,"types":[]},{"text":"impl Freeze for F4","synthetic":true,"types":[]},{"text":"impl Freeze for F8","synthetic":true,"types":[]},{"text":"impl Freeze for V48","synthetic":true,"types":[]},{"text":"impl Freeze for V358","synthetic":true,"types":[]},{"text":"impl Freeze for V37","synthetic":true,"types":[]},{"text":"impl Freeze for SpliceError","synthetic":true,"types":[]}];
implementors["cjdns_ctrl"] = [{"text":"impl Freeze for CtrlMessage","synthetic":true,"types":[]},{"text":"impl Freeze for ErrorData","synthetic":true,"types":[]},{"text":"impl Freeze for PingData","synthetic":true,"types":[]},{"text":"impl Freeze for CtrlMessageData","synthetic":true,"types":[]},{"text":"impl Freeze for CtrlMessageType","synthetic":true,"types":[]},{"text":"impl Freeze for ErrorMessageType","synthetic":true,"types":[]}];
implementors["cjdns_hdr"] = [{"text":"impl Freeze for DataHeader","synthetic":true,"types":[]},{"text":"impl Freeze for RouteHeader","synthetic":true,"types":[]},{"text":"impl Freeze for SwitchHeader","synthetic":true,"types":[]},{"text":"impl Freeze for ContentType","synthetic":true,"types":[]}];
implementors["cjdns_keys"] = [{"text":"impl Freeze for CJDNSKeys","synthetic":true,"types":[]},{"text":"impl Freeze for CJDNSKeysApi","synthetic":true,"types":[]},{"text":"impl Freeze for CJDNS_IP6","synthetic":true,"types":[]},{"text":"impl Freeze for CJDNSPrivateKey","synthetic":true,"types":[]},{"text":"impl Freeze for CJDNSPublicKey","synthetic":true,"types":[]}];
implementors["cjdns_sniff"] = [{"text":"impl !Freeze for Sniffer","synthetic":true,"types":[]},{"text":"impl Freeze for Message","synthetic":true,"types":[]},{"text":"impl Freeze for Content","synthetic":true,"types":[]},{"text":"impl Freeze for ConnectError","synthetic":true,"types":[]},{"text":"impl Freeze for SendError","synthetic":true,"types":[]},{"text":"impl Freeze for ReceiveError","synthetic":true,"types":[]}];
implementors["cjdns_snode"] = [{"text":"impl Freeze for Opts","synthetic":true,"types":[]},{"text":"impl Freeze for Config","synthetic":true,"types":[]},{"text":"impl Freeze for NODE_NAME_RE","synthetic":true,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()